server:
  port: 8080

spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lprs?unicode=true&serverTimezone=GMT&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

my:
  name: zhou
  age: 20

spring.resources.static-locations: file:E://workspace-idea/lprs/Spring-bootDemo/res/
